name: Build & Release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3


      - name: Build Bannerlord Cheats
        run: dotnet build BannerlordCheats.csproj --configuration Release -p:GameFolder="${{github.workspace}}\Bannerlord" -p:UseNuGetAssemblies="True"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BannerlordCheats
          path: ${{github.workspace}}\Bannerlord\Modules
