name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.x
        env:
          DOTNET_NOLOGO: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Setup BUTR GPR
        uses: actions/setup-dotnet@master
        with:
          source-url: https://nuget.pkg.github.com/BUTR/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOTNET_NOLOGO: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Build BannerlordCheats
        run: dotnet build BannerlordCheats.csproj  --configuration Release -p:GameFolder="$PWD\game"
        env:
          DOTNET_NOLOGO: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          
      - name: Get Versions
        id: versions
        run: |
          $Version = Get-Content .\Directory.Build.props | Select-String -Pattern "<Version>([\d.]+)<\/Version>" | % { $($_.Matches.Groups[1]).Value }
          echo "::set-output name=mod_version::$Version"

      - name: Package Mod Files
        run: 7z a -tzip BannerlordCheats-${{steps.versions.outputs.mod_version}}.zip ./game/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BannerlordCheats-${{steps.versions.outputs.mod_version}}
          path: ./game/*
